Bugfix 112 : Change error message if username or email is not found
LangkaWS/sortir.com pull request #116
Opened 2021-02-11 21:40 UTC by LangkaWS

closes #112

2021-02-11 22:00 UTC, Neario approved these changes, later dismissed

2021-02-11 22:04 UTC, Heroponne commented on src/Security/Authenticator.php
>          }
Vu que toute l'app côté utilisateur est en français, pourquoi ne pas continuer sur cette lancée ?

2021-02-11 22:05 UTC, Heroponne requested changes
Passer le message en français

2021-02-11 22:24 UTC, LangkaWS commented on src/Security/Authenticator.php
>          }
Oui j'y ai pensé mais si tu fais une erreur dans le mdp, ça met "Invalid credentials". Et j'arrive pas à trouver où ce message est défini dans Symfony. Donc si tu trouves, fais-toi plaiz

2021-02-11 23:51 UTC, Heroponne approved these changes, later dismissed

2021-02-12 08:22 UTC, Neario approved these changes

2021-02-12 08:24 UTC, Heroponne approved these changes

2021-02-12 08:34 UTC, merged