Feature 3 : Gérer le profil
LangkaWS/sortir.com pull request #60
Opened 2021-02-03 09:21 UTC by Neario

close #3

2021-02-03 11:29 UTC, LangkaWS requested changes
Pas mal de choses à revoir, ce sont des suggestions, à toi de voir :)

2021-02-03 11:29 UTC, LangkaWS commented on public/css/profile.css
> +.profile_wrap {
Tout ce qui est CSS on verra plus tard. Il y a Bootstrap qui gère pour le moment, le reste on centralisera dans un fichier main.css (pour tout ce qui est classes communes comme les titres des pages, etc.), et séparer après les trucs plus spécifiques.

2021-02-03 11:29 UTC, LangkaWS commented on src/Controller/UserController.php
> +use App\Form\MyProfileType;
Plutôt utiliser un UserType pour garder la cohérence dans le naming.

2021-02-03 11:29 UTC, LangkaWS commented on src/Controller/UserController.php
> +            $user->setIsActive(true);
Tu peux enlever ce morceau de code :
Ton $user, tu fais un $this->getUser(). Donc les propriétés isAdmin et isActive proviennent de l'objet User, donc ont pour valeurs `true` ou `false`.

2021-02-03 11:29 UTC, LangkaWS commented on src/Controller/UserController.php
> +        $profile = $this->createForm(MyProfileType::class, $user);
Plutôt préférer utiliser $form que $profile (uniformité du naming, par défaut Symfony l'appelle $form, comme ça dans ta méthode tu sais que tu parles du formulaire et pas du "profil")

2021-02-03 11:29 UTC, LangkaWS commented on src/Controller/UserController.php
> +            $user->setPassword($hash);
Là je ne suis pas trop d'accord. Quand ton utilisateur va sur son profil, on lui demande son mdp (requis ; pour valider les changements je pense). Sauf que s'il se plante dans son mdp, ce nouveau mdp est enregistré en bdd et l'utilisateur a "changé" son mot de passe sans faire exprès.
Je préfèrerais laisser le mdp en non requis et si l'utilisateur ne le renseigne pas, on garde celui en bdd. Généralement sur les sites on ne demande pas le mdp pour éditer son profil.

2021-02-03 11:29 UTC, LangkaWS commented on src/Controller/UserController.php
> +            $user->setCampus($user->getCampus());
Sur toute cette partie, en fait ton code ne fait rien...
Pour résumer : 
- L'utilisateur arrive sur la page. Ton controller fait un getUser et montre les infos.
- L'utilisateur modifie ce qu'il a envie de modifier et soumet le formulaire. Par exemple il change son numéro de téléphone qui n'était pas renseigné (null) et met 0123456789.
- Le formulaire arrive dans ton controller avec les infos actualisées de $user.
- Il fait un `$user->getPhone()` : renvoie 0123456789
- Puis fait un `$user->setPhone($user->getPhone())` éq. `$user->setPhone(0123456789)` (or l'atrtibut phone est déjà égal à 0123456789
Tout ce que tu as besoin de faire c'est `$em->flush()`. D'ailleurs c'est comme ça quand tu génères automatiquement le CRUD avec Symfony ;)

2021-02-03 11:29 UTC, LangkaWS commented on src/Controller/UserController.php
> +        }
Là tu l'avais déjà dit, il manque un return

2021-02-03 11:29 UTC, LangkaWS commented on src/Controller/UserController.php
> +    public function myProfile(Request $request, EntityManagerInterface $em, UserPasswordEncoderInterface $encoder): Response
Plutôt renommer la méthode en `edit`, pour correspondre au CRUD de Symfony (new, show, edit, delete)

2021-02-03 11:29 UTC, LangkaWS commented on src/Form/MyProfileType.php
> +class MyProfileType extends AbstractType
Renommer plutôt en UserType

2021-02-03 11:29 UTC, LangkaWS commented on src/Form/MyProfileType.php
> +    public function __construct(Security $security){
Détail de mise en forme : mettre l'accolade à la ligne (uniformité du code)

2021-02-03 11:29 UTC, LangkaWS commented on src/Form/MyProfileType.php
> +                'options' => ['attr' => ['class' => 'password-field']],
Si la class n'est pas utilisée -> à enlever (n'est apparemment pas utilisé par Bootstrap ni dans ton CSS)

2021-02-03 11:29 UTC, LangkaWS commented on templates/base.html.twig
> +        <link href="{{ asset('css/profile.css')}}" rel="stylesheet">
cf commentaire css

2021-02-03 11:29 UTC, LangkaWS commented on templates/user/myProfile.html.twig
> +{% extends 'base.html.twig' %}
Renommer en show.html.twig (uniformité du nommage, nom automatique donné par Symfony quand tu fais un CRUD).
De plus, ce fichier est utilisé pour afficher un profil utilisateur, que ce soit le sien ou celui d'un autre ; ça évitera de devoir faire 2 fichiers html qui seront quasi identiques.
Il faut juste rajouter des blocs if selon si l'utilisateur est sur sa page ou non.

2021-02-03 11:29 UTC, LangkaWS commented on templates/user/myProfile.html.twig
> +    </div>
En utilisant `{{ form_widget(profile) }}` Symfony te génère tout seul les div ;) ça fait moins de lignes de codes à faire :)
La mise en page tu pourras la faire avec le CSS.

2021-02-03 11:29 UTC, LangkaWS commented on templates/user/myProfile.html.twig
> +<div class="profile_wrap">
Ta div ici ne sert à rien car tu te retrouves avec le code :
```
<main>
    <div class="profile_wrap">
        <h3>Mon profil</h3>
        <form>...</form>
    </div>
</main>
```
Pour la mise en forme, tu peux regarder ce que Symfony crée avec le CRUD, il fait une table, ça t'évite les display: flex, dans tous les sens dans le CSS qui ne flexent même pas :/

2021-02-03 11:29 UTC, LangkaWS commented on templates/user/myProfile.html.twig
> +        <p>{{app.user.campus}}</p>
Un petit campus qui s'est perdu par là ^^

2021-02-03 13:00 UTC, Neario commented on templates/user/myProfile.html.twig
> +<div class="profile_wrap">
sisi , ça flex en column , afin d'aligner avecv align-items au centre de ma page

2021-02-03 13:41 UTC, Neario commented on src/Controller/UserController.php
> +            $user->setIsActive(true);
fait

2021-02-03 13:41 UTC, Neario commented on src/Controller/UserController.php
> +        $profile = $this->createForm(MyProfileType::class, $user);
Ok

2021-02-03 13:42 UTC, Neario commented on src/Controller/UserController.php
> +            $user->setCampus($user->getCampus());
Compris

2021-02-03 13:42 UTC, Neario commented on src/Controller/UserController.php
> +        }
return ajouter vers app_home

2021-02-03 13:42 UTC, Neario commented on src/Controller/UserController.php
> +    public function myProfile(Request $request, EntityManagerInterface $em, UserPasswordEncoderInterface $encoder): Response
fait

2021-02-03 13:43 UTC, Neario commented on src/Form/MyProfileType.php
> +class MyProfileType extends AbstractType
fait

2021-02-03 13:43 UTC, Neario commented on src/Form/MyProfileType.php
> +    public function __construct(Security $security){
OK

2021-02-03 13:43 UTC, Neario commented on src/Form/MyProfileType.php
> +                'options' => ['attr' => ['class' => 'password-field']],
Ok

2021-02-03 13:44 UTC, Neario commented on templates/user/myProfile.html.twig
> +    </div>
suppression des divs inutile

2021-02-03 13:45 UTC, Neario commented on templates/user/myProfile.html.twig
> +        <p>{{app.user.campus}}</p>
corrigé c'était un test

2021-02-03 14:19 UTC, LangkaWS requested changes
Attention, quand j'édite et j'enregistre sans mettre de mot de passe, j'ai l'erreur suivante : 
"Expected argument of type "string", "null" given at property path "password"."

2021-02-03 14:19 UTC, LangkaWS commented on src/Controller/UserController.php
> +            'controller_name' => 'ManageProfileController',
le controller_name si tu n'en as pas besoin, tu peux l'enlever :)

2021-02-03 14:19 UTC, LangkaWS commented on templates/user/edit.html.twig
> +        {{ form_row(profile.campus) }}
Tout ça équivaut à {{ form_widget(profile) }} en fait ^^ ça économise 10 lignes :D

2021-02-03 15:32 UTC, Neario commented on src/Controller/UserController.php
> +            'controller_name' => 'ManageProfileController',
fait

2021-02-03 15:34 UTC, Neario commented on templates/user/edit.html.twig
> +        {{ form_row(profile.campus) }}
OK

2021-02-03 15:35 UTC, Neario commented on templates/user/myProfile.html.twig
> +{% extends 'base.html.twig' %}
CRUD activé , nommage modifié

2021-02-03 15:35 UTC, Neario commented on templates/base.html.twig
> +        <link href="{{ asset('css/profile.css')}}" rel="stylesheet">
Css viré pour le moment

2021-02-03 15:36 UTC, Neario commented on templates/user/edit.html.twig
> +        {{ form_row(profile.campus) }}
Oui exact

2021-02-03 15:52 UTC, Heroponne commented on src/Controller/UserController.php
> +    public function index(UserRepository $userRepository): Response
Peut-être juste mettre / en route, et pas /user sinon l'url sera /user/user

2021-02-03 15:57 UTC, Heroponne commented on templates/user/index.html.twig
> +
on n'en a pas encore besoin pour le moment (peut-être la partie admin), ais bon, juste chenger le block body par main et le title

2021-02-03 15:59 UTC, Heroponne approved these changes, later dismissed

2021-02-03 16:31 UTC, Neario commented on src/Controller/UserController.php
> +    public function index(UserRepository $userRepository): Response
fait

2021-02-04 15:24 UTC, Heroponne commented on src/Entity/User.php
> +        return (string) $this->email;
Le souci n'avait pas été réglé ?  c'est normal que le getusername renvoie encore l'email ?

2021-02-04 15:25 UTC, Heroponne commented on src/Form/UserType.php
> +                ])
mettre un 'required' => false

2021-02-04 15:26 UTC, Heroponne submitted a review, later dismissed

2021-02-04 15:38 UTC, LangkaWS requested changes
A rajouter peut-être après avoir merge une première fois : 
Quand l'utilisateur clique sur "Mon profil" il voit son profil et il doit appuyer sur "modifier" pour pouvoir modifier les champs ; ça éviterait les modifications accidentelles. - A noter que c'est pas demandé dans le PDF des cas d'utilisation ni dans le description produit

2021-02-04 15:38 UTC, LangkaWS commented on src/Controller/UserController.php
> +    }
A retirer car les nouveaux utilisateurs sont créés via la méthode register

2021-02-04 15:38 UTC, LangkaWS commented on src/Controller/UserController.php
> +     * @Route("/{id}", name="user_show", methods={"GET"})
Tu pourrais faire comme pour edit, utiliser le {username} plutôt que l'id :)

2021-02-04 15:38 UTC, LangkaWS commented on src/Controller/UserController.php
> +        }
La condition sert à vérifier si l'utilisateur essaie de modifier le profil de quelqu'un d'autre ?
Dans ce cas, c'est peut-être plus indiqué d'enlever {username} du path, et à chaque fois que tu dois référer au user, tu fais un $this->getUser(), à voir.

2021-02-04 15:38 UTC, LangkaWS commented on src/Entity/User.php
> +        return (string) $this->email;
Non, là il faut que tu pull develop pour avoir le fix.

2021-02-04 15:38 UTC, LangkaWS commented on src/Entity/User.php
> +    }
Et tu peux retirer celle-là une fois que tu as re pull et merge develop dans ta feature.

2021-02-04 15:38 UTC, LangkaWS commented on src/Form/UserType.php
> +                ])
Sur le phone, j'ai un message d'erreur comme quoi il est requis.
Le phone n'est pas requis en bdd, donc pas besoin d'avoir cette restriction :)

2021-02-04 15:38 UTC, LangkaWS commented on templates/user/edit.html.twig
> +    {#{{ include('user/_form.html.twig', {'button_label': 'Update'}) }}#}
Ici tu peux utiliser le include _form qui est donné par défaut, ça ne marche pas ?
Au passage tu as une balise </div> mais pas de balise ouvrante ^^

2021-02-04 15:38 UTC, LangkaWS commented on templates/user/new.html.twig
> +{% endblock %}
Comme l'inscription se passe sur register.html.twig, tu peux supprimer ce fichier

2021-02-04 15:38 UTC, LangkaWS commented on templates/user/index.html.twig
> +{% endblock %}
Comme on n'affichera pas la liste des utilisateurs, tu peux supprimer ce fichier aussi

2021-02-04 15:39 UTC, LangkaWS commented on src/Entity/User.php
> +        return (string) $this->email;
C'est parce qu'il lui manque le bugfix je pense.

2021-02-04 17:18 UTC, Neario commented on src/Controller/UserController.php
> +    }
Viré

2021-02-04 17:19 UTC, Neario commented on src/Entity/User.php
> +        return (string) $this->email;
Fix pull

2021-02-04 17:19 UTC, Neario commented on src/Entity/User.php
> +    }
fix fait

2021-02-04 17:19 UTC, Neario commented on src/Form/UserType.php
> +                ])
Corrigé

2021-02-04 17:20 UTC, Neario commented on templates/user/edit.html.twig
> +    {#{{ include('user/_form.html.twig', {'button_label': 'Update'}) }}#}
le bonton update inclus ne fonctionne pas

2021-02-04 17:20 UTC, Neario commented on templates/user/new.html.twig
> +{% endblock %}
viré

2021-02-04 17:20 UTC, Neario commented on templates/user/index.html.twig
> +{% endblock %}
supprimé

2021-02-04 17:20 UTC, Neario commented on src/Controller/UserController.php
> +     * @Route("/{id}", name="user_show", methods={"GET"})
fait

2021-02-04 17:21 UTC, Neario commented on src/Form/UserType.php
> +                ])
fait

2021-02-04 17:21 UTC, Neario commented on src/Entity/User.php
> +        return (string) $this->email;
Fait

2021-02-04 18:22 UTC, LangkaWS commented on templates/user/edit.html.twig
> +    {#{{ include('user/_form.html.twig', {'button_label': 'Update'}) }}#}
Ah bizarre j'avais testé ça avait bien fonctionné

2021-02-04 19:20 UTC, LangkaWS approved these changes
C'est bon j'ai plus de commentaires :D

2021-02-05 07:53 UTC, Heroponne approved these changes
ok pour moi :)

2021-02-05 11:10 UTC, merged