Feature 5 - Créer une sortie
LangkaWS/sortir.com pull request #68
Opened 2021-02-08 09:27 UTC by Heroponne

A vérifier :

- [ ] création de sortie fonctionnelle
- [ ] le champ du campus fait bien apparaître le campus de l'utilisateur actuel
- [ ] si on clique sur le DD des villes et qu'on en sélectionne une, le DD des lieux change avec les lieux associés à cette ville
- [ ] si on clique sur le DD des lieux sans avoir sélectionné de ville, tous les lieux apparaissent dans le DD des lieux
- [ ] si on sélectionne un lieu, son adresse et ses coordonnées apparaissent dans les champs respectifs
- [ ] si on clique sur Créer, l'état de la sortie est "en création"
- [ ] si on clique sur Publier, l'état de la sortie est "ouverte" (ça dépend de l'id de vos états en BDD)
- [ ] sur le form d'annulation de sortie, il n'y a qu'un seul bouton d'annulation qui apparait (même dans l'inspecteur d'élément)
- [ ] ce form d'annulation fonctionne toujours

2021-02-08 09:48 UTC, LangkaWS commented
Attention j'ai pu créer une sortie avec une date limite d'inscription postérieure à la date de début.

2021-02-08 09:48 UTC, LangkaWS commented
Autre chose, la liste des lieux s'affiche bien lorsqu'on ne sélectionne pas de ville mais il serait peut-être judicieux de mettre quand même un required sur la ville pour être sûr du lieu sélectionné, ou bien indiquer dans "adresse" le CP et la ville du lieu. Par exemple j'ai 2 fois le lieu "gare" avec comme adresse "place de la gare". Le lieu apparaît 2 fois dans la liste mais on ne sait pas dans quelle ville il est.

2021-02-08 09:56 UTC, LangkaWS commented
Attention, en incluant un 'campusShown' dans OutingType, le bouton edit ne fonctionne plus.

2021-02-08 10:10 UTC, LangkaWS requested changes

2021-02-08 10:10 UTC, LangkaWS commented on templates/outing/_form.html.twig
> +<button class="btn btn-secondary {{ secondary_class }}" value="{{ secondary_value }}" name="{{ secondary_name }}">{{ secondary_button_label|default('Supprimer') }}</button>
A vérifier si cela (les {{ var }} n'impacte pas les fichiers /outing/*.twig qui include ce fichier.

2021-02-08 10:10 UTC, LangkaWS commented on templates/outing/cancel.html.twig
> +    </script>
J'aime pas trop cette partie là, de créer un bouton pour l'enlever avec du JS. Il vaudrait peut-être mieux ajouter une variable que l'on passe quand on fait le render depuis le controller (en même temps qu'on passe $outing et $form), par exemple $action = (new/edit/cancel).
Et faire dans ce fichier un if action === new -> mettre tel et tel bouton, else if action === edit, etc.
D'autant plus que sûrement que le bouton cancel sera en danger et pas en primary.

2021-02-08 10:15 UTC, Heroponne commented on templates/outing/_form.html.twig
> +<button class="btn btn-secondary {{ secondary_class }}" value="{{ secondary_value }}" name="{{ secondary_name }}">{{ secondary_button_label|default('Supprimer') }}</button>
Si, ça change, j'ai du faire des retouches dans ton formulaire d'annulation, par exemple !

2021-02-09 14:25 UTC, LangkaWS commented
Petit bug :
![image](https://user-images.githubusercontent.com/60548795/107377157-f168c980-6aea-11eb-9da6-31a532b6a206.png)

Tu peux le corriger avec la PR ou avec une nouvelle issue, comme tu veux

2021-02-09 15:34 UTC, LangkaWS commented on src/Controller/OutingController.php
> +        ]);
Pourquoi tu re-set l'organizer et le campus quand on édite ?
Normalement il n'y a que l'organisateur qui peut éditer une sortie (peut-être les admins aussi ?), mais organizer et campus ne sont pas stockés dans $outing que tu récupères en paramètre ?

2021-02-09 15:34 UTC, LangkaWS commented on templates/outing/new.html.twig
> +    {{ include('outing/_form.html.twig')}}
Comment qu'il manque un espace ici !!

2021-02-09 15:40 UTC, Heroponne commented on templates/outing/new.html.twig
> +    {{ include('outing/_form.html.twig')}}
Toi je vais pas te louper, à la prochaine empty end-line que t'auras pas !! xD je corrige ça tout de suite, c'est vrai que c'est moche cet espace manquant, je me sens tout chose en regardant ce bout de code

2021-02-09 15:46 UTC, Heroponne commented on src/Controller/OutingController.php
> +        ]);
Alors oui tout à fait, j'ai un peu rapidement pensé en mode new Outing et pas en mode l'outing existe déjà !

2021-02-09 15:56 UTC, LangkaWS submitted a review, later dismissed
Allez pesé, c'est emballé !

2021-02-10 12:35 UTC, Neario submitted a review, later dismissed
Rien à dire , propre

2021-02-11 10:36 UTC, LangkaWS approved these changes

2021-02-11 11:31 UTC, Neario approved these changes

2021-02-11 12:03 UTC, merged