Feature 7
LangkaWS/sortir.com pull request #72
Opened 2021-02-09 14:00 UTC by Neario

2021-02-09 16:47 UTC, Heroponne commented on src/Controller/OutingController.php
> +        $this->addFlash('success', 'Votre annulation à la sortie à bien été prise en compte');
Je rajouterais une restriction ici, comme j'en ai mise une dans la feature 8 ! parce que si un malin s'amuse à modifier le bouton "se désinscrire" de la sortie suivante à laquelle il est inscrit, et change l'id par celui de la sortie dont la date de cloture est dépassée mais dont il veut se désinscrire, bah il peut !

2021-02-09 16:48 UTC, Heroponne commented on templates/outing/index.html.twig
> +                    {% for participant in outing.participants %}
mettre le bouton d'inscription dans la condition else du if que tu as fait juste après, histoire de ne pas pouvoir s'inscrire à nouveau ! c'est pas directement lié à la feature mais bon, tant qu'à faire :)

2021-02-09 16:50 UTC, Heroponne requested changes
rajouter une restriction pour la désinscription dans le controller, et mettre le s'inscrire dans le else du if que tu as fait dans la view !

2021-02-09 16:54 UTC, LangkaWS commented on src/Controller/OutingController.php
> +        $this->addFlash('success', 'Votre annulation à la sortie à bien été prise en compte');
Euh la date limite d'inscription s'applique que à l'inscription non ? Il n'y a pas de limite sur la désinscription ?

2021-02-09 17:03 UTC, LangkaWS commented on templates/outing/index.html.twig
> +                    {% for participant in outing.participants %}
Attention si tu mets le else du if, si la registrationDeadline <= date('now'), tu as le bouton s'inscrire qui popera

2021-02-10 12:12 UTC, LangkaWS requested changes

2021-02-10 12:12 UTC, LangkaWS commented on src/Controller/OutingController.php
> +        $this->addFlash('success', 'Votre annulation à la sortie à bien été prise en compte');
"En tant que participant inscrit à une sortie, je peux me désister **tant que la sortie n'a pas débuté**. En cas de désistement, la place devient libre pour un autre participant si la date limite d'inscription n'est pas dépassée."

Il faut que la désinscription soit possible si la sortie n'a pas commencé ;)

2021-02-10 12:12 UTC, LangkaWS commented on templates/outing/index.html.twig
> +                        {% if app.user == participant and outing.registrationDeadLine > date('now')  %}
Là je mettrais outing.startDate plutôt que outing.registrationDeadLine (voir commentaire sur le controller).
Je mettrais aussi une égalité stricte (===), c'est ce qui est conseillé "par défaut" à part si tu as spécifiquement besoin d'une égalité pas stricte.

2021-02-10 12:12 UTC, LangkaWS commented on templates/outing/index.html.twig
> +                    {% for participant in outing.participants %}
En fait je pense que ce serait plus sur la feature inscription que si user n'est pas dans participants, alors il y a le bouton d'inscription. Je vais faire une issue dessus.

2021-02-10 16:29 UTC, LangkaWS submitted a review, later dismissed

2021-02-10 17:26 UTC, Heroponne commented on src/Controller/OutingController.php
> +        $this->addFlash('success', 'Votre annulation à la sortie à bien été prise en compte');
oui c'est vrai :)

2021-02-10 19:52 UTC, Heroponne submitted a review, later dismissed
Well done !

2021-02-11 12:08 UTC, Heroponne approved these changes, later dismissed
Purrfect !

2021-02-11 12:09 UTC, LangkaWS submitted a review, later dismissed

2021-02-11 12:36 UTC, LangkaWS approved these changes

2021-02-11 13:30 UTC, Heroponne approved these changes
Ok pour moi !

2021-02-11 13:30 UTC, merged