Feature 4 : Afficher les sorties par campus
LangkaWS/sortir.com pull request #74
Opened 2021-02-10 16:19 UTC by LangkaWS

Il faut surtout tester le filtre. Mon code est peut-être un peu dégueulasse, j'attends vos retours :)

2021-02-10 20:24 UTC, Heroponne commented on templates/outing/index.html.twig
> +            </select>
Pourquoi que y'a que deux campuuuuuus ?

2021-02-10 21:31 UTC, Heroponne requested changes
Bah il m'a l'air plutôt très propre, ce code, et le filtre fonctionne très bien, bravo !! Juste standardiser le dropdown des campus et c'est parfait :)

2021-02-11 10:32 UTC, LangkaWS commented on templates/outing/index.html.twig
> +            </select>
AH. Je les ai mis à la patte et j'en ai que deux dans ma bdd xD Merci pour l'avoir trouvée celle-là x)

2021-02-11 13:01 UTC, Neario approved these changes

2021-02-11 13:16 UTC, Heroponne commented on src/Entity/Town.php
>      public function getId(): ?int
Très important, ça ! Bien vu :D

2021-02-11 13:24 UTC, Heroponne approved these changes
Impec !

2021-02-11 13:39 UTC, merged